### ISSUE TITLE
The request compatibility level JAVA_17 could not be set.

### ISSUE THREAD

**Issue by FUNDAI** [Giggitybyte/SleepWarp#7]
I didn't install other mod when i launch my game it's crash.By the way my JRE version is 1.8

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config sleepwarp.mixins.json for mod sleepwarp
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config sleepwarp.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.3 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more

**Comment by Giggitybyte** [comment]
What is your Minecraft version number?

**Comment by FUNDAI** [comment]
It's 1.16.5

Luke Triano ***@***.***> 於 2022年5月29日 週日 上午2:02 寫道：

**Comment by FUNDAI** [comment]
It's 1.16.5

**Comment by katrina1704** [comment]
I have this problem too, I just got it today, It didn't even open the game properly and gave me the same error. It's also 1.16.5 for game version

**Comment by Giggitybyte** [comment]
It would seem I forgot that the older versions of Minecraft run on an older version of Java when I was backporting the 1.18 version; I'll have to change my code a bit for the 1.16 version to make it usable with Java 8. I'll do this when I get the chance.

For now, if you're able, the easiest way to work around this is to install the latest version of Java and point Minecraft to that new Java version in your launcher.

**Comment by Giggitybyte** [comment]
Long overdue, finally adressed:
**1.16**: https://github.com/Giggitybyte/SleepWarp/releases/download/backport-fix-1.16.4/sleepwarp-1.2.0+1.16.5.jar
**1.17**: https://github.com/Giggitybyte/SleepWarp/releases/download/backport-fix-1.17.1/sleepwarp-1.2.0+1.17.1.jar
